name: Use Herald > build test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  herald:
    name: apply herald rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install packages
        run: npm install
      - name: Dry run Herald rules with checked in dist/
        id: herald-dist
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: herald_rules_for_build/*.json
          DEBUG: '*'
          dryRun: true
      - name: Rebuild binary
        run: npm run build
      - name: Dry run Herald rules with rebuilt dist/
        id: herald-rebuilt
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: herald_rules_for_build/*.json
          DEBUG: '*'
          dryRun: true
